### ISSUE TITLE
'preset' missing from graph_annotations settings

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/jekyll-open-sdg-plugins#104]
@brockfanning I think `preset` is missing from the graph annotation settings

**Comment by brockfanning** [comment]
Not sure if we covered this elsewhere, but the reason was that the "preset" idea doesn't work out when using the config form. Because the config form sets all values, the preset stuff gets ignored, because it's designed to defer to any other values that are set. But I think we can close this because we now have the target lines and series breaks in dedicated config settings.
